# Generated by Django 4.2.29 on 2026-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('ring', 'Кольцо'), ('earrings', 'Серьги'), ('necklace', 'Подвеска'), ('bracelet', 'Браслет')], default='ring', max_length=20, verbose_name='Категория')),
                ('material', models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро'), ('rose', 'Розовое золото'), ('platinum', 'Платина'), ('black', 'Чёрное золото'), ('meteorite', 'Метеорит')], default='gold', max_length=20, verbose_name='Материал')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Цена (₽)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('characteristics', models.TextField(blank=True, verbose_name='Характеристики')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
