# Generated by Django 4.2.29 on 2026-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=40, verbose_name='Тема отзыва')),
                ('full_text', models.TextField(max_length=600, verbose_name='Текст отзыва')),
                ('date', models.DateTimeField(verbose_name='Дата публикации полная')),
            ],
        ),
    ]
