# Generated by Django 4.2.29 on 2026-04-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_product_image_url_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
