# Generated by Django 4.2.29 on 2026-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('ring', '💍 Кольцо'), ('earrings', '✨ Серьги'), ('necklace', '📿 Подвеска'), ('bracelet', '🔗 Браслет')], default='ring', max_length=20, verbose_name='Тип изделия')),
                ('material', models.CharField(choices=[('gold', '🟡 Золото'), ('silver', '⚪ Серебро'), ('rose', '🌸 Розовое золото'), ('platinum', '🤍 Платина'), ('black', '⚫ Чёрное золото'), ('meteorite', '☄️ Метеорит (Новинка)')], default='gold', max_length=20, verbose_name='Материал')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='Название изделия')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '★ 1'), (2, '★★ 2'), (3, '★★★ 3'), (4, '★★★★ 4'), (5, '★★★★★ 5')], default=5, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
