# Generated by Django 4.2.29 on 2026-04-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_color',
            field=models.CharField(choices=[('gold', 'Золото'), ('silver', 'Серебро'), ('rose', 'Розовое золото'), ('platinum', 'Платина'), ('black', 'Чёрное золото')], default='gold', max_length=20, verbose_name='Цвет изделия'),
        ),
    ]
