# Generated by Django 4.2.29 on 2026-04-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_color',
        ),
        migrations.AddField(
            model_name='review',
            name='material',
            field=models.CharField(choices=[('gold', '🟡 Золото'), ('silver', '⚪ Серебро'), ('rose', '\U0001fa77 Розовое золото'), ('platinum', '🤍 Платина'), ('black', '⚫ Чёрное золото'), ('meteorite', '☄️ Метеорит (Новинка)')], default='gold', max_length=20, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product_type',
            field=models.CharField(choices=[('ring', '💍 Кольцо'), ('earrings', '✨ Серьги'), ('necklace', '📿 Подвеска'), ('bracelet', '🔗 Браслет')], default='ring', max_length=20, verbose_name='Тип изделия'),
        ),
    ]
