# Generated by Django 4.2.29 on 2026-04-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_product_color_review_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='material',
            field=models.CharField(choices=[('gold', '🟡 Золото'), ('silver', '⚪ Серебро'), ('rose', '🌸 Розовое золото'), ('platinum', '🤍 Платина'), ('black', '⚫ Чёрное золото'), ('meteorite', '☄️ Метеорит (Новинка)')], default='gold', max_length=20, verbose_name='Материал'),
        ),
    ]
